version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7156:8080"
    volumes:
      - ./data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/races.db
      
  frontend:
    build:
      context: ./running-races-ui
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api